//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibreria_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Autor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Autor()
        {
            this.tb_Libro = new HashSet<tb_Libro>();
        }
    
        public int aut_id { get; set; }
        public string aut_nom { get; set; }
        public string aut_ape { get; set; }
        public byte[] aut_foto { get; set; }
        public string aut_pais { get; set; }
        public string aut_user_reg { get; set; }
        public System.DateTime aut_fec_reg { get; set; }
        public string aut_user_mod { get; set; }
        public Nullable<System.DateTime> aut_fec_mod { get; set; }
        public bool aut_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Libro> tb_Libro { get; set; }
    }
}
