//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibreria_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Almacen()
        {
            this.tb_Ejemplar = new HashSet<tb_Ejemplar>();
        }
    
        public int alm_id { get; set; }
        public string alm_sec { get; set; }
        public string alm_desc { get; set; }
        public string alm_user_reg { get; set; }
        public System.DateTime alm_fec_reg { get; set; }
        public string alm_user_mod { get; set; }
        public Nullable<System.DateTime> alm_fec_mod { get; set; }
        public bool alm_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ejemplar> tb_Ejemplar { get; set; }
    }
}
