//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibreria_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Requerimiento()
        {
            this.tb_Requerimiento_detalle = new HashSet<tb_Requerimiento_detalle>();
        }
    
        public int req_id { get; set; }
        public int edi_id { get; set; }
        public Nullable<System.DateTime> req_fec_emi { get; set; }
        public string req_user_reg { get; set; }
        public System.DateTime req_fec_reg { get; set; }
        public string req_user_mod { get; set; }
        public Nullable<System.DateTime> req_fec_mod { get; set; }
        public bool req_state { get; set; }
    
        public virtual tb_Editorial tb_Editorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Requerimiento_detalle> tb_Requerimiento_detalle { get; set; }
    }
}
