//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibreria_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaLibrosRentados
    {
        public int rent_id { get; set; }
        public System.DateTime rent_fec { get; set; }
        public Nullable<System.DateTime> rent_fec_dev { get; set; }
        public int ejem_id { get; set; }
        public int lib_id { get; set; }
        public string lib_nom { get; set; }
        public Nullable<int> aut_id { get; set; }
        public string aut_nom { get; set; }
        public string aut_ape { get; set; }
        public Nullable<int> gen_id { get; set; }
        public string gen_desc { get; set; }
        public int edi_id { get; set; }
        public string edi_nom { get; set; }
    }
}
